.github/PULL_REQUEST_TEMPLATE.md

This PR proposes to add a PR template

[CEN-1049] Add PR template

---

.devops/code-review-pipelines.yml

This PR proposes to add a code review pipeline (Azure DevOps) which can be executed on PR.
The pipeline send JaCoCo reports to SonarCloud for analysis. Test for correct handling of differential metrics, like line and branch coverage, is to be postponed to other PRs

[CEN-1020] Pipeline code review

---

.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml
Dockerfile
manifests/deployment.yml

This PR proposes an Azure DevOps pipeline to deploy the batch acquirer in DEV k8s cluster.
- A new Deploy Pipeline
- A very basic Docker File, needed by the pipeline
- A basic Deployment manifest for k8s, which should be refined with environment sources
This PR resolves two problems
- Deploy the application in a controlled environment for testing and quality improvement
- Setup the ground to distribute the app as a docker image
Live test in Azure DevOps. I attach the k8s log to show that the pod crashes due to lack of a proper environment, which will be fixed in other PRs.

[CEN-1021] Deploy Pipeline

---

entrypoint.sh

This PR restores the HPAN_SERVICE_URL to the DEV endpoint and turn on log debug messages.
HPAN_SERVICE_URL set to https://api.dev.cstar.pagopa.it
LOG_LEVEL set to DEBUG
The HPAN_SERVICE_URL was previously pointed to the UAT endpoint due to problems in the DEV environment. Now the service is newly available on DEV so the URL must be updated.
Log level has been raised to DEBUG to ease troubleshooting activities.

Cen 1081 override hpan service url

---

ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
ops_resources/example_config/application_postgresql.yml

This PR removes an unnecessary environment variable by reusing the one already defined for the HPAN service trust store file path.
Removed specific env variable
This PR simplifies the runtime configuration by removing one of the (too) many env variables needed at the moment

[CEN-1099] collapsed TKM trust store env to the HPAN one

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterScheduler.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/encryption/EncryptUtil.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/HpanStoreService.java
pom.xml

This PR proposes to fix code comments to comply with `javadoc` standard and manage UML architectural diagram inline at package or class level.
-Fix syntax of javadoc comments in different modules
- Add maven plugi to generate doc with command `mvn javadoc:javadoc`
- Add a `tasklet` to empower javadoc `doclet` to parse plantuml
This change is required to allow management of doc and code in the same workflow

[CEN-1116] Fix Javadoc and Add Plantuml support

---

entrypoint.sh

Removed hardcoded export statements from entrypoint.sh. Those statements were needed during the initial effort to put the application into k8s but now they must be removed in favour of configmap entries.
Removed export statements from entrypoint.sh
Hardcoding env variables is a bad practice, thus removing it

[CEN-1017] Removed hardcoded export statements

---

pom.xml

See: https://www.lunasec.io/docs/blog/log4j-zero-day/
This PR updates the version of the dependency log4j which is flawed by a severe vulnerability that has been addressed in the latest version 2.15.0
Updated log4j version to 2.15.0
Fix for 0-day vulnerability

[CEN-1144] Update dependency to resolve vulnerability

---

manifests/deployment.yml

This PR enabled the encryption of the output files by leveraging GPG keys.
- Added mount point for encryption key file
The key file is needed locally on the pod to perform encryption

[CEN-1084] Mounting secret containing PGP public key in /app_certs_in

---

manifests/deployment.yml

This PR fixes the encryption of output file that was broken due to the public key incorrectly loaded into the pod.
- Decoding of base64-encoded public key using init containers
- (temporary) override of configmap ACQ_BATCH_INPUT_PUBLIC_KEYPATH value
This change is needed in order to restore encryption functionality

Cen 1084 fix key not readable

---

entrypoint.sh
manifests/deployment.yml

This PR removes all init steps related to PagoPA K8s configuration from the entrypoint.sh, which should be generally applicable.
Removed init steps from entrypoint.sh, and performing them with deployment init containers on PagoPA K8s manifest
In order to make Dockerized versions of the application generally available we must remove all custom configuration steps form entrypoint.sh / Dockerfile

[CEN-1146] Removed k8s init steps from entrypoint.sh

---

pom.xml

see: https://www.lunasec.io/docs/blog/log4j-zero-day/
This PR updates the version of the dependency log4j to the latest release (2.15.0) which addresses a severe 0-day.
Updated dependency
Securify fix

[CEN-1144] Updated log4j to 2.15.0

---

entrypoint.sh

This PR removes static export statements from the entrypoint.sh file. Those statements were needed when porting the application to k8s but now should be removed in favour of values coming from configmaps.
Removed export statements
Hardcoding runtime parameters is a bad practice, but was temporarily needed

[CEN-1086] Remove export statements from entrypoint.sh

---

manifests/deployment.yml

Backport of changes introduced in release 1.1.0 in order to enable PGP encryption of output files in DEV environment.
For details refer to the original PRs:
-  https://github.com/pagopa/rtd-ms-transaction-filter/pull/120
- https://github.com/pagopa/rtd-ms-transaction-filter/pull/122

[CEN-1084] Enable PGP encryption (cherrypick from release 1.1.0)

---

entrypoint.sh
manifests/deployment.yml

This PR removes all init steps related to PagoPA K8s configuration from the entrypoint.sh, which should be generally applicable.
For details see:
- https://github.com/pagopa/rtd-ms-transaction-filter/pull/123

[CEN-1146] Removed k8s init steps from entrypoint.sh (#123)

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/sftp/pom.xml
pom.xml

This PR bumps the version in the POM files to 1.1.0.
It also removes the BPD prefix from the generated artifact (.jar)
- Updated version to 1.1.0
- Removed bpd prefix from generated .jar
The version advertised in the POM files was not aligned with the release branch.

[CEN-1205] Bump release from 1.0.2 to 1.1.0

---

pom.xml

This PR upgrades the dependency log4j2 to the latest release at this day (2.17.0), which address recent vulnerabilities.
- Upgraded log4j2 from 2.15.0 to 2.17.0
- Fix for potential security issues

[CEN-1189] Upgraded log4j2 library to latest release (2.17.0)

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/InboundTransaction.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/mapper/LineAwareMapperTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorValidatorTest.java

This PR makes the field VAT, previously mandatory, optional.
- Field VAT is now optional
- Minor refactoring in test classes
- Field VAT is required to be optional in the release 1.1.0

[CEN-1220] Field VAT now optional

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientTest.java

This PR addresses two vulnerabilities related to zip slip injection reported by SonarCloud on the HpanRestClientImpl.java class.
- Added input validation for filenames coming from external archives
- The vulnerability is reported as severe (E) therefore must be addressed

[CEN-1223] Solve vulnerabilities reported by sonarcloud

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
integration/sftp/pom.xml
integration/sftp/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/TransactionSftpConnector.java
integration/sftp/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/TransactionSftpConnectorTest.java

This PR updates sshd-sftp and sshd-core to the latest version which are not affected by CVEs. It also updated the jsch dependency for compatibility reasons.
- Updated dependencies: sshd-sftp, sshd-core, jsch
- Minor stylistical changes
This PR addresses vulnerabilities affecting current project's dependencies

[CEN-1224] Updated sshd-sftp, sshd-core and jsch to latest version

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/InboundTransaction.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorValidatorTest.java

This PR adds size constraint to fields missing it.
- Added @size constraint to data model
- Updated test suite
This PR aligns the implementation with the specifics

[CEN-1225] Add @Size constraint to fields without any

---

manifests/deployment.yml

This PR removes hard-coded values from the manifest in favour of externally defined values (from configmap managed via cstar-infrastractur IAAS).
Removed hardcoded configmap values from manifest
Addressing technical debt

[CEN-1155] Remove hard-coded environment values

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/config/HpanRestConnectorConfig.java
integration/rest/src/test/resources/stubs/mappings/ade_sas.json
integration/rest/src/test/resources/stubs/mappings/download.json
integration/rest/src/test/resources/stubs/mappings/list.json
integration/rest/src/test/resources/stubs/mappings/publickey.json
integration/rest/src/test/resources/stubs/mappings/rtd_sas.json
integration/rest/src/test/resources/stubs/mappings/salt.json
integration/rest/src/test/resources/stubs/mappings/upload.json
integration/rest/src/test/resources/stubs/mappings/uploadNotAuthorized.json
pom.xml

This PR adds a User-Agent header to all HTTP requests made. The user agent contains the build version information (the Maven project.version as defined in the pom.xml) that will be used to track the application version in use by the acquirers.

[CEN-1400] Add UserAgent with version to HTTP requests

---

.github/CODEOWNERS

This PR adds a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location) file to the repository.
- added CODEOWNERS file inside .github directory
- listed Giovanni Mancini and Alberto Re as code owners
Having a CODEOWNERS is a best practice

[CEN-1410] Add CODEOWNERS file to repository

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionChecksumTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/writer/ChecksumHeaderWriter.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionChecksumTaskletTest.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/StoreService.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/StoreServiceImpl.java
core/src/test/java/it/gov/pagopa/rtd/transaction_filter/service/StoreServiceTest.java

This PR introduces a header in the output AdE aggregation files containing the checksum (SHA256) of the input file provided from the Acquirer on which aggregation have been computed.
- Add header callback to AdE FlatFileWriter
- Since aggregations loose any relation with the transactions that originated them we want to be sure that if an input file is being processed multiple times, accidentally or not, the derived aggregations will carry the information of the originating file thus enabling CentroStella to discard all incoming files except for the first one.

[CEN-1542] Add header with checksum on AdE aggregation files

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
pom.xml

This PR updates the POM version from 1.1.0 to 1.2.0 in order to proceed with the release of the new version.

[RTD-25] Bump version to 1.2.0 in all POMs

---

integration/rest/src/main/resources/config/rest-client.properties

This PR adds the connection parameter in properties file to retrieve the bin range download links.
- Added url in `rest-client.properties`
The parameter will be needed to download the bin range files.

[RTD-84] Add bin range service URL in properties

---

.github/CODEOWNERS

This PR propose to remove Alberto Re and add Andrea Morabito to code owners.
- modified code owners file to add Andrea Morabito as code owner.
Every developer of CSTAR team has to be code owner.

[CSMP-2] Remove Alberto Re, add Andrea Morabito and Tommaso Lencioni to code onwers

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/validator/BasicResponseEntityValidator.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/validator/ResponseEntityValidator.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/validator/ValidatorConfig.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/validator/BasicResponseEntityValidatorTest.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/validator/GenericDto.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/validator/ValidatorUtility.java

This PR adds a basic http response validator.
- Add interface and basic implementation to validate a `ResponseEntity<T>` object
- Configuration class to create javax Validator instance as Bean for the entire project
- Unit tests of basic validator
This kind of validation is required in multiple methods so I propose to add a generic validator for every kind of response entity. If any custom validation is needed it's possible to extends the basic validator and adds the custom checks.
The Bean of javax.validation.Validator is added to prevent the multiple creation of factories and instances around the codebase.

[TAE-45] Add basic http validator

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
pom.xml

This PR updates the pom version to the 1.2.1 version.
- Updates pom version
This update is required to release the latest version of the batch service including the download of sender ade ack files and the replacement of fake abi code with acquirer fiscal code.

[RTD-183] update pom version to 1.2.1

---

Dockerfile

This PR proposes to change the docker runtime image to allow the compatibility with arm processors.
- Changed docker runtime image
The previous image was not compatible with arm processors.

[RTD-197] Change docker runtime image for arm compatibility

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java

This PR proposes to improve the unit tests of batch service with two changes. The first one changes some assertions to make them more specific, the second one improves the output file creation.
- Change some assertions
- Improve file creation
The unit tests were not solid and they failed in some circumstances during the docker build due to poor management in file creation and to poor assertion precision in verifying some condition.

[TAE-63] Corrections on unit tests 

---

Dockerfile
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java

This PR proposed to merge branch develop into master to bring the latest fixes on docker file and some unit tests.
- Dockerfile
- Some assertions in unit tests
There is a problem with the docker image compatibility with the arm processors and with the execution of docker build due to some poor designed assertions.

[RTD-203] Align master with develop branch after bugfix

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to set the default log level to INFO in the application properties. It's suggested to modify the [presets](https://docs.pagopa.it/centrostella-1/centro-stella/instructions-for-agenzia-delle-entrate-mandate/how-to-join/03.-configure-the-batch-service/install-the-software/how-to-install-jar-version/define-environment-variables) in the guide by removing the row `export LOG_LEVEL_RTD_TRANSACTION_FILTER=INFO`, which is redundant at this point. 
- Changed the log level in applications yml to INFO
The current log level is set to DEBUG and then it's overwritten through the environment script during the batch service configuration. To avoid this pass and to minimize the numbers of environment variables it is better to set INFO as default and let the user customize when needed.

[RTD-254] set default log level to INFO

---

integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientTest.java

This PR proposes to change, inside the method `cleanup()` in class `SenderAdeAckRestClientTest`, the method call from `resetAll()` to `resetToDefaultMappings()`. 
The `resetAll() `may cause the tests to be order dependent and that may lead to some subtle and unexpected errors. `resetToDefaultMappings()` will restore the wiremock status at his initial configuration so it guarantees the independency among tests.

[RTD-260] fix after method in unit test class

---

core/pom.xml
integration/rest/pom.xml
pom.xml

This PR proposes to add the postgresql driver dependency to support an external database, beyond the default DB in-memory, for spring batch executions.
- Add postgresql driver dependency
- Minor refactor on pom files
As is the batch service does not support the connection with an external database to support the spring batch executions.
This PR adds the support to connect a postgresql in case the acquirers want to use an external database to keep track on executions.

[RTD-248] Add postgresql support for spring batch

---

README.md
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/InboundTransaction.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java

This PR proposes to update the README file with the new GitBook page link.
- Add new GitBook page link
- Replace edit-link for GitBook
The README is currently not up to date and it is better to keep it updated with the new integration procedure.

[RTD-263] update REAME

---

app/pom.xml

This PR proposes to change the file name of jar file into a generic one (not binded to current version).
- Changed jar `finalName`
To make the jar downloadable from the `latest` version it is required to remove the specific version from file name. The download link will be the following: `https://github.com/pagopa/rtd-ms-transaction-filter/releases/latest/download/rtd-ms-transaction-filter.jar`

[RTD-288] Change executable jar file name

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to remove the not supported logging properties from application.yml files.
- Removed logging.config and logging.console
Typo from previous released version: `logging.config` allow to bind an external datasource to persist the application log but we are not currently supporting this feature.

[RTD-290] remove not supported logging properties

---

app/src/main/resources/config/application.yml
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/config/HpanRestConnectorConfig.java
integration/rest/src/main/resources/config/rest-client.properties
integration/rest/src/test/resources/stubs/mappings/ade_sas.json
integration/rest/src/test/resources/stubs/mappings/download.json
integration/rest/src/test/resources/stubs/mappings/fiscalCodeMap.json
integration/rest/src/test/resources/stubs/mappings/list.json
integration/rest/src/test/resources/stubs/mappings/publickey.json
integration/rest/src/test/resources/stubs/mappings/rtd_sas.json
integration/rest/src/test/resources/stubs/mappings/salt.json
integration/rest/src/test/resources/stubs/mappings/senderAdeAckDownload.json
integration/rest/src/test/resources/stubs/mappings/senderAdeAckList.json
integration/rest/src/test/resources/stubs/mappings/upload.json
integration/rest/src/test/resources/stubs/mappings/uploadNotAuthorized.json
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to remove the hardcoded user agent headers and make them parametrizable from `application.yml`.
- Remove hardcoded set to user-agent headers
- Parametrize user-agent headers in application file
- Remove useless and maintenance expensive user agent in wiremock stubs
As is the batch service has the user-agent headers hardcoded in source code and do not change with new releases. To fix that behaviour it is better to parametrize the user-agent version with the application version from pom file.

[RTD-287] Parametrize application version

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml

This PR proposes to fix the typo in the environment variable `ACQ_BATCH_DBS_PASSWORD`.
- Fixed typo 
`ACQ_BATCH_DBS_PASSWORD` has a different prefix from the other related environment variables. In order to uniform with the other ones it's suggested to refactor into `ACQ_BATCH_DB_PASSWORD`.

[RTD-289] fix typo on ACQ_BATCH_DBS_PASSWORD

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchInputFileChecksumDisabledTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTaskletTest.java

This PR proposes to delete the empty log files at the end of the job run. As is there are 4 files generated per run and most of the time they are empty.
The feature has required a different management of the file channels. As is the channels stay open till the batch is ended and that means it is not possible to check if the files are empty during the execution of the batch (because they will always be). Therefore now the channels are closed at the start of the file management tasklet execution (always the last step of the batch) and the empty files inside the log directory are removed.
- Rework the management of file channels
- Add the removal routine of empty log files in the file management tasklet
- Improvement of dependency injection of some services
- Minor improvements
In order to …

[RTD-364] Delete of empty log files

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to remove the parametrized user-agent application version in `application.yml` for a fixed version manually upgradable.
- Change application version parse strategy in application.yml
Some acquirers links the `application.yml` externally to the jar file with the option `--spring.config` and the `@project.version@` string is not correctly translated into the application version. Even if it is explicitly discouraged to link an external properties, we cannot prevent the acquirers from doing it. Therefore i suggest to upgrade manually the version inside the properties like it's done with the pom version.

[RTD-390] Set explicit application version in properties

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemProcessListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemReaderListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessor.java

This PR proposes to enrich the stdout log in case of parse or validation errors.
- Improve log message in listeners
The acquirers must understand why a record has been discarded and which field of the input record is flawed.

[RTD-375] Error log improvement

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java

This PR proposes to fix a bug in the settings of apache http client. In particular when a proxy is set the upload file request ignore it (meanwhile every feign client request pass through it). 
- Add proxy setting to the apache http client
Some acquirers have a proxy between the host and PagoPA gateway. That may cause problems (like DNS or firewall issues) when the batch service tries to send a file.

[TAE-145] Fix proxy in PUT upload file request

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to update the pom version to 1.2.4.
- Update pom version
- Update properties version
The batch service must be released to the version 1.2.4

[RTD-366] update pom version to 1.2.4

---

.github/CODEOWNERS

This PR proposes to add Andrea Petreti to codeowners file.

[CSMP-5] add Andrea Petreti to codeowners

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
pom.xml

This PR proposes to improve the null check on proxy set. 
- Improve null check with proxy
- Upgrade lombok version

[RTD-394] Improve proxy null check

---

Dockerfile
api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/TransactionFlatFileItemReader.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/HpanListRecoveryTaskletTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/writer/HpanWriterTest.java
integration/jpa/pom.xml
integration/rest/pom.xml
pom.xml

This PR proposes to upgrade the dependencies to the last version stable and compatible.
- Reworked pom files to improve the version management of the dependencies
- Removed useless dependencies
- Minor change to adapt the code to the version bumps
The analysis with the tool Trivy highlighted the CVEs present in the dependencies of the batch service. To fix those it is better to update the dependencies to the last version.

[RTD-423] Upgrade dependencies

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to parametrize the hpan list url with a environment variable.
- Changed rest-client.hpan.list.url property with the new custom variable `ACQ_BATCH_HPAN_LIST_URL`
The old endpoint that provide the hpan file is deprecated and it will be soon replaced with a new version. To avoid to release a new version of batch service in the future, it is better to let acquirer configure the change of URL through a env variable.
The base path of the product will remain fixed and only the last part of URL can be configured.

[RTD-427] Parametrize hpan list url

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to bump the pom version from 1.2.4 to 1.2.5.
- Upgraded pom and application version
In order to release the new version of batch service it is required to upgrade the version in pom and application.yml

[RTD-428] pom version bump to 1.2.5

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchInputFileChecksumDisabledTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTaskletTest.java

This PR proposes to fix a bug introduced with last changes into file management tasklet. 
- Fixed string to replace in path
This PR fixes a bug related to the replacement of `\` to `/`, change required in order to make the application system independent.

[RTD-431] bugfix replacing slash for system independent check

---

Dockerfile
api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/TransactionFlatFileItemReader.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchInputFileChecksumDisabledTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/HpanListRecoveryTaskletTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTaskletTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/writer/HpanWriterTest.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to promote the branch dev into branch master.
- Reworked and upgraded dependencies
- Bump version to 1.2.5
- Changed docker images
- Changed default value on some env variables related to hpan validation
- Minor fix for code review pipeline
- Minor changes
In order to release the new version of batch service it is needed to merge the branch dev into branch master.

[RTD-429] Merge branch 'dev' into branch 'master'

---

.github/workflows/anchor.yml

Add a github action to implement security checks
- New GitHub Action
Insert Security checks in CI/CD

[RTD-444] Add security check via Github Action

---

app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to fix the `logging.file` property that right now it's not working.
- Fixed logging.file property
After the spring boot version bump to 2.7.3 (in the release 1.2.5 of batch service) `logging.file` has became deprecated in favor of `logging.file.name`.

[RTD-441] fix logging.file property after spring boot version bump

---

.github/workflows/anchor.yml

This PR proposes to align the dev branch with the master one.
The step of security check has been merged directly to master and the change is not present on dev. That do not let the step to run on the new PRs created from a feature branch to dev branch.

Alignment of 'dev' branch with 'master' branch

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
pom.xml

This PR proposes to remove the plantUML dependency and CVE-2022-1379.
- remove plantUML dependency from pom.xml
The dependency generates a critical CVE and it's better to be removed since it's not even utilized.

[RTD-491] remove plantUML dependency (and CVE)

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java

This PR proposes to fix a weak cryptography warning.
- Replace java.Random with java.security.SecureRandom library
Sonar pointed out this security hotspot in the batch service. It can be solved with the use of java.security.SecureRandom library.

[RTD-502] fix weak cryptography

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/encryption/EncryptUtil.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/encryption/exception/PGPDecryptThrowable.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/AdeTransactionsAggregate.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/InboundTransaction.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/RawInputLine.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/PanReaderStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/JobListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemProcessListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemReaderListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemWriterListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionReaderStepListener.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/PGPFlatFileItemReader.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/TransactionFlatFileItemReader.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/HpanListRecoveryTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SaltRecoveryTasklet.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/writer/HpanWriter.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/JobListenerTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemReaderListenerTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorValidatorTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/PGPFlatFileItemReaderTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/HpanListRecoveryTaskletTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SaltRecoveryTaskletTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/writer/HpanWriterTest.java
app/src/main/java/it/gov/pagopa/rtd/transaction_filter/RtdTransactionFilterApplication.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/config/HpanRestConnectorConfig.java

This PR proposes to fix most of code smells and bugs on the codebase.
- Massive fixes of code smells and bugs
In order to give the acquirers a good and valid product, it is required to solve most of code smells and bugs reported by sonar.

[RTD-505] remove most code smells and bugs

---

pom.xml

This PR proposes to upgrade the versions of some dependencies. 
- Upgrade dependencies version in pom file
There has been found some CVEs on commons-io and snakeyaml dependencies. In order to resolve those CVE it is required to upgrade the version.

[RTD-519] upgrade dependencies version

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionSenderRestTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionSenderRestTaskletTest.java

This PR proposes to fix the upload retry mechanism.
- Fixed upload retry
- Added unit test
When the upload PUT fails, the batch service must retry with a delay between the requests.

[RTD-524] fix upload retry

---

app/src/main/resources/config/application.yml
integration/rest/src/main/resources/config/rest-client.properties
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to define the url property for the ade ack download confirmation. 
- Add property in application.yml files
The batch service needs the url for the new ack confirmation endpoint.

[RTD-557] define the property for the ack received url endpoint

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestConnector.java

This PR proposes to add the method on feign client for ack download confirmation.
- Add PUT method
The batch service needs a method in feign client to forward the http call to APIM. It is required to complete the feature implementation.

[RTD-555] add put method to feign client for ack download confirmation

---

api/batch/src/main/resources/config/transactionFilterStep.properties
app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to add a new directory in the workdir of the batch service, named `pending`. The directory will serve as deposit for the files that failed the upload. It will be placed as subdirectory of the current `workdir/output` and managed by the batch service. Therefore there is no need for the sender to create and configure the directory.
- Add new property
In order to implement the feature of re-upload of the files that failed the upload, it's required to define a new directory to place those files after upload failed.

[RTD-651] Add new directory "pending"

---

api/batch/src/main/resources/config/transactionFilterBatch.properties
api/batch/src/main/resources/config/transactionFilterStep.properties
app/src/main/resources/config/application.yml
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml

This PR proposes to align the pending directory definition with the error and success ones. It means the directory can be defined by the sender through environment variable if they want to customize the location or naming. The default remains as subdirectory of output folder: `output/pending`.
- Refactor `pending` directory definition
In order to have the same behaviour among the folders the sender can define, it's required a slight refactor in the `pending` property definition.

[RTD-651] refactor pending directory

---

.devops/pr-title-yml

This PR proposes to add an action to check if PR title starts with a conventional commit type.
- New github action to check if PR type is one listed here https://github.com/commitizen/conventional-commit-types/blob/master/index.json
Enable semantic versioning

chore:Check PR title

---

pom.xml

This PR proposes to solve the CVE on jettison 1.2 package.
- Upgrade spring boot version from 2.7.3 to 2.7.4
- Upgrade snakeyaml version from 1.32 to 1.33
The jettison package 1.2 has a CVE with severity `HIGH`. In order to fix it's only needed to upgrade the spring boot version dependency.

[RTD-611] upgrade spring boot and snakeyaml version

---

.github/workflows/pr-title.yml
.github/workflows/release.yml

[RTD-662] Add workflows for semantic versioning

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTaskletTest.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientImpl.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientTest.java

This PR proposes to fix a bug on the temporary folder creation for sender ade ack files downloaded. The bug consists in not deleting the directory when there are no files to download.
- Bug fix on sender ade ack rest client
- Updated unit tests
When there are no ade ack files to download, the temporary directory will exists in the file system until the so cleans it up. To prevent this the rest client is going to delete the temp folder when no ade ack files have been download (or acknowledged to the backend).

[RTD-687] fix empty temp folder of sender ade ack files

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java

This PR proposes to replace the `PGPFlatFileItemWriter` with a standard `FlatFileItemWriter` to remove the encryption at then end of the file writing in the ade workflow.
- Replace item writer
The introduction of MultiResourceItemWriter pointed out a bad practice in the file encryption routine. In the first place I'm going to replace the custom item writer in favor of the standard one (subject of this PR) and in the next PR the encryption routine is going to be put in a dedicated tasklet.

[RTD-731] replace encryption item writer with standard item writer

---

acceptance_tests/ack_confirm/script_ack_confirm.bash
acceptance_tests/ack_confirm/setenv.sh

This PR proposes to add the ack confirm acceptance test.
- add script 
- add custom env
The ack confirm feature needs to be tested and it's been done with this process:
- starting from batch service, send a file
- recover the file from ade/in to create fake ack
- inject fake ack
- wait ack-ingestor pipeline
- download the ack
- check if the file is still available to download
components tested: batch service, decrypter, aggregates-ingestor pipeline, ack-ingestor pipeline, file register

chore: [RTD-672] add ack confirm acceptance test

---

.releaserc.json

This PR proposes to add the configuration file for semantic release github action.
- add json file

chore: [RTD-662] add releaserc.json for semantic-release

---

.github/PULL_REQUEST_TEMPLATE.md

feat: Fix PR template

---

LICENSE

This PR proposes to add the EUPL 1.2 license to the repository.
- add license file

chore: [RTD-851] add LICENSE file

---

api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTaskletTest.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to promote 4 fixes to the branch master. It will lead to the release v1.3.2
- fix jackson CVEs by bumping version from 2.13.4 to 2.14.0
- pom version re-align
- fix sender-ade-ack property
- mitigation for sender ack FileExistsException

fix: Promotion to master

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/TransactionAggregationReaderProcessor.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/StoreService.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/StoreServiceImpl.java
core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/store/AggregationData.java
core/src/test/java/it/gov/pagopa/rtd/transaction_filter/service/StoreServiceTest.java

This PR proposes to fix the bug on the field `totalAmount` due to cast to int during the processing.
- convert the entire chain to Long values
The sum of big amount values turns to negative number when it goes over the int max value.

fix: [RTD-915] bugfix int overflow on field totalAmount

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to upgrade the app pom version to 1.3.3.
- bump pom version
the batch service must be released.

chore: bump pom version to v1.3.3

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java

This PR proposes to fix the number generation of negative values replacing the long with a UUID truncated to 20 chars.
- changed secure random method with a random UUID
The random number generated is also negative and it creates troubles to senders. The `nextLong()` method in java 8 does not support the upperbound feature, therefore the SecureRandom has been replaced with a random UUID without dash and truncated at 20 chars.

fix: [RTD-955] random generator gives negative numbers

---

app/src/main/resources/logback-spring.xml

This PR proposes to fix the application log rolling policy.
- changed `logback-spring.xml`
The file log rolling policy is bugged since the logback configuration xml file has been introduced. The policy has been restored manually inside the config file.

fix: [RTD-956] application.log rotation policy

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to align the pom version with the new version of the batch service.
- update pom version
The latest release has disaligned the pom version due to miss-configuration in the github action semantic release.

fix: [RTD-1037] align pom version

---

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/FileReportRestClient.java
integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/FileReportRestClientImpl.java
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/FileReportRestClientTest.java
integration/rest/src/test/resources/stubs/mappings/fileReport.json

This PR proposes to implement the rest client to consume the file report APIs.
- Add rest client and narrow integration tests

[RTD-836] implement rest client

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java

This PR adds comments on new methods in the codebase.
- java comments
- added 1 unit test

[RTD-1105] add docs on methods

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to update the pom version to 1.5.0.
The promotion to master will bring a new minor release, therefore it is needed to update the pom version.

[RTD-1106] update pom version to 1.5.0

---

acceptance_tests/file_report/file_report_without_folder.sh

This PR proposes to add an acceptance test for file report feature.
- add acceptance test
With this change we can test the behavior of the batch service in case of missing report folder.

chore: [RTD-1111] Test with missing report directory

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTaskletTest.java

This PR proposes to upgrade the file management tasklet test class to junit5.

[RTD-1229] upgrade to Junit5

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/DeleteOutputFilesEnum.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTaskletTest.java

This PR proposes to refactor the file management tasklet in order to improve the readability and maintainability of the codebase. Beside it fixes some bugs on movement to pending folder and error folder.
The following scenario are now fixed:
- step 1 checksum COMPLETED; step 2 transaction process FAILED, both with the same input file as parameter. Atm the tasklet evaluates only the first step and move the input file into the `success` folder. The desiderata is that all the steps with the same filename as parameter are taken in consideration and only the worst status is evaluated (FAILED in this case).
- the pgp files that fail the send step go into the `pending` folder independently of `deleteProcessedFiles` and `deleteOutputFiles` flags.
- `error` folder is restored to its original …

[RTD-1230] refactor tasklet

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/DeleteOutputFilesEnum.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTaskletTest.java

This PR proposes a complete refactor on the file management tasklet.
- refactor tasklet
- upgrade to JUnit5 for tasklet tests
- add conditional branches on main job

fix: [RTD-735] refactor tasklet file management

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java

This PR proposes to fix a bug on the path on windows.
- add resolver to handle output path
A sender is trying to integrate with windows. A bug has been found in path management.

fix: [RTD-1286] bugfix path for windows compatibility

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java

This PR proposes to fix a bug in file management on Windows OS.

fix: [RTD-1328] fix file management on Windows OS

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to align the pom version to the new release 1.5.1
- bump pom version

chore: [RTD-1329] bump pom version to 1.5.1

---

api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to promote to master branch from dev. This will trigger the release v1.5.1.
- #333 
- #334

fix: Promotion to master - v1.5.1

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to bump the pom version of Batch Service to 2.0.0.
In order to release the batch service, the pom version needs to be bumped.

[RTD-1348] bump pom version to 2.0.0

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java

This PR proposes to partially restore the usage of resolver to works on Windows like OS.

fix: [RTD-1357] bugfix path resolver

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionSenderRestTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/TransactionSenderRestTaskletTest.java

This PR proposes to fix the retry feature on SAS token failure.

fix: [RTD-1356] fix retry on sas failure

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/TransactionMaskPolicy.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/TransactionMaskPolicyImpl.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/TransactionMaskPolicyTest.java

This PR proposes to add the policy to mask the pan in a InboundTransaction object.
- add policy classes

[RTD-1366] add mask policy for transaction

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemReaderListener.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchInputFileChecksumDisabledTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemReaderListenerTest.java

This PR proposes to apply the transaction masking in reader listener component. It is responsible to log the lines that failed the parse in the reading phase.

[RTD-1368] apply mask in reader listener

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchInputFileChecksumDisabledTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchSplittingTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java

This PR proposes to replace JUnit asserts with the AssertJ library.
AssertJ assertions are much more readable and much easier to debug.

[RTD-1369] replace junit assert with assertj

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemWriterListener.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemWriterListenerTest.java

This PR proposes to apply the mask policy of transaction in the writer listener, right before logging on file.

[RTD-1373] apply mask policy in writer listener

---

.github/CODEOWNERS
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemProcessListener.java

This PR proposes to move the mask policy command inside the code block responsible for logging on file. In this way the policy is not applied when not necessary and the ecologists will thank us.
- Apply policy only when necessary
- Add Luca Consalvi to codeowners

[RTD-659] apply mask policy only when necessary in process listener

---

api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to bump the pom version to 2.0.1 in order to make a new release.

[RTD-1371] bump pom version to 2.0.1

---

pom.xml

This PR proposes to fix a typo in the pom version

[RTD-1371] typo version

---

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/TransactionMaskPolicyImpl.java

This PR proposes a minor refactor on mask policy.

chore: [RTD-1366] minor refactor on mask

---

api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/CustomIteratorItemReader.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/FileReportItemReader.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to fix a bug that shows up when the job scheduler is active. Some step do not refresh correctly some states on second (and successive) run.
- Introduce StepScope bean on file report 
- Reset iterator correctly on iterable itemReader
- bump pom version to 2.0.2
- update bouncy castle to 1.72.2
- update commons-fileupload to 1.5
- update spring boot to 2.7.9

fix: [RTD-1427] fix bug on successive scheduled runs

---

api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/CustomIteratorItemReader.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/FileReportItemReader.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to promote in master the dev branch.
- Fix the bug on scheduled runs, in particular those after the first one
- bump version of various packages

fix: Promotion to master, fix bug on scheduled runs

---

acceptance_tests/splitting_ade_batch_service/script_splitting.bash
acceptance_tests/splitting_rtd_batch_service/script_splitting_rtd.bash

This PR proposes to update the acceptance tests with a minor changes

chore: [RTD-1674] acceptance test update

---

.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/scan.yml
.github/workflows/upload-jar.yml

This PR proposes to improve the CI/CD.
- fix send slack notification
- add job to automate the docker image push into ghcr
- add job to automate the upload of the jar artifact into release
- pin actions sha
- replace grype with trivy

chore: [RTD-2080] add action to publish docker image

---

.github/workflows/pr-title.yml
.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/scan.yml
.github/workflows/upload-jar.yml

This PR proposes to promote to main branch the improvements of the CI/CD. including the fix of scan and many more. see #364

chore: Promotion to master - publish docker image

---

.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/scan.yml
api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to make some minor changes on github actions and trigger a new release with the new CD pipeline

fix: [RTD-2135] minor fix on actions

---

.devops/deploy-pipelines.yml

This PR proposes to update the java version in the deploy pipeline from 8 to 17.

chore: update java version in deploy pipeline

---

.devops/deploy-pipelines.yml
.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/scan.yml
api/batch/pom.xml
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

fix: promotion to master - minor fix on actions

---

.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/upload-jar.yml

This PR proposes to refactor the release pipeline.
In particular there are changes in the triggers of publish image and upload jar workflows.
the schema changes in this way:
```
on push:
release 
├── (if new version) publish image
└── (if new version) upload jar
```
to:
```
on push:
- release
on release published:
- publish image
- upload jar
```
The jobs are no longer part of the same release workflow. They are separated and triggered by the publishing of a new github release. 
In this way the `(if new version)` condition is delegated to the trigger and no longer manually handled.
To manually trigger the workflows (publish and upload) is needed to manually publish a release

chore: fix deploy actions

---

.github/workflows/publish-image.yml
.github/workflows/release.yml
.github/workflows/upload-jar.yml

chore: promotion to master - fix deploy actions

---

.github/workflows/publish-image.yml
.github/workflows/upload-jar.yml

This PR adds the env for the upload step and adds the qemu setup to build image for different platforms.

chore: fix actions responsible of publish and upload

---

.github/workflows/publish-image.yml
.github/workflows/upload-jar.yml

see #371
- add secret for upload step
- add docker setup qemu to build image

chore: promotion to master - fix actions responsible of publish and upload

---

.github/workflows/publish-image.yml
.github/workflows/upload-jar.yml

This PR proposes to change the permissions on CD actions to allow publishing and uploading

chore: fix permissions on actions

---

.github/workflows/publish-image.yml
.github/workflows/upload-jar.yml

chore: promotion to master - fix github action permissions

---

.github/workflows/publish-image.yml

This PR proposes to move the permission section in the publish image workflow

chore: move permissions on publish action

---

.github/workflows/publish-image.yml

chore: promotion to master - move permissions on publish action

---

.github/workflows/publish-image.yml

chore: promotion to master - restore bot token

---

.github/workflows/scan.yml

This PR fixes CVE scan github action's. Now when no CVEs were founds the action complete successfully

chore: fix cve scan when no cve were founds

---

.github/workflows/scan.yml

* fix cve scan when no cve was found
* fix cve scan when no cve was found

chore: fix cve scan when no cve were founds (#380)

---

.github/workflows/scan.yml
.github/workflows/send-notification.yml

This PR proposes to refactor the scan workflow to work with github environments.

chore: promotion to main - refactor scan workflow

---

.github/workflows/scan.yml

add condition to trigger a job even if the previous one fails
see #388

chore: promotion to master - fix slack action

---

.github/workflows/scan.yml

This PR change the field evaluated in the job of send notification

chore: evaluate the correct field on job condition

---

.github/workflows/scan.yml

evaluate the correct field on job condition
see #391

chore: promotion to master - fix action condition

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java

chore: [RTD-2540] fix flaky test

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java

chore: [RTD-2540] fix flaky test (#397)
[RTD-2540]: https://pagopa.atlassian.net/browse/RTD-2540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Promote to PROD

---

api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java

chore: [RTD-2569] fix flaky test

---

api/batch/pom.xml
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/BatchExecutor.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/config/AppConfig.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/PathResolver.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/BatchExecutorTest.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/utils/PathResolverTest.java
api/pom.xml
app/pom.xml
app/src/main/resources/config/application.yml
core/pom.xml
integration/jpa/pom.xml
integration/pom.xml
integration/rest/pom.xml
integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java
ops_resources/example_config/application.yml
ops_resources/example_config/application_hbsql.yml
pom.xml

This PR proposes to fix the symlink resolution of input directory.

fix: promotion to master - symlink resolution

---

acceptance_tests/symlinks/symlinks.bash
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java
api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SelectTargetInputFileTasklet.java
api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SelectTargetInputFileTaskletTest.java

This PR proposes to fix a bug in input file selection when the folder is a symlink.
The folder is not resolved correctly to the real path.

fix: [TAE-327] fix file selection in symlink folder
