.devops/code-review-pipelines.yml
This PR proposes to fix the `SonarPrepare` task in code-review pipeline to send all reports (surefire, jacoco and jacoco aggregate) to Sonar Cloud
- Fix regex in `SonarPrepare` task
This PR is motivated by the fact that Coverage of 0.0% we are seeing on SonarCloud seems quite unreasonable, so we have to guarantee that all available reports are sent to sonar
This has been tested by running the code review pipeline in a dedicated branch, but only a run on master can tell us if the changes can fix the problem
=> [CEN-1020] Send to sonar all jacoco reports

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/mapper/InboundTransactionFieldSetMapper.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorValidatorTest.java
This PR re-enables the correct handling of the MCC field. The field value was hardcoded to '0000' on output files during the cashback period but the intended functionality must be restored in the 1.1.0. 
- restore functionality of MCC field
- re-declared checked exception (seems the more correct correct)
- solved Sonarcloud smell by replacing string literal with constant
- MCC field must be restored in order to ship the release 1.1.0
=> [CEN-1198] Remove hard-coded 0000 MCC

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
This PR adds an header containing the input file checksum (SHA256) to the RTD (CSTAR.*) output files produced by the batch job.
- Add header callback also to RTD ItemWriter
- Having this information also on RTD files could be useful to avoid ingesting the same file multiple times accidentally
=> [RTD-12] Add header callback also to RTD ItemWriter

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java, api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/PreventReprocessingFilenameAlreadySeenTasklet.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/PreventReprocessingFilenameAlreadySeenTaskletTest.java, core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/TransactionWriterService.java, core/src/main/java/it/gov/pagopa/rtd/transaction_filter/service/TransactionWriterServiceImpl.java, core/src/test/java/it/gov/pagopa/rtd/transaction_filter/service/TransactionWriterServiceTest.java
This PR adds a step to the batch process that verifies if the current input file, solely given its filename, has been processed in previous jobs. If so, the current job exit immediately and a custom exception is thrown.
- Add new Tasklet responsible for checking current input filename against opened file channels
- The use case was, by accident, already implemented, but the error wasn't gracefully handled
=> [RTD-31] Prevent processing same input filename twice

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/TransactionAggregationReaderProcessor.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java
This PR adds the actual replacement of field acquirer id in case the fake ABI is mapped to a fiscal code.
- Replace of abi with mapped fiscal code (if the entry exists, do nothing otherwise)
- Add unit test of a complete job run with a `abiToFiscalCode` map set. Assert on the output file.
- Refactor an existing unit test
Replace a fake abi with the correct fiscal code during the processing step of transactions input file.
=> [TAE-37] Replace fake abi in trx process

app/src/main/resources/config/application.yml, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml
This PR proposes to disable the date validation check on the hpans file by default.
- Changed the sensible default for the environment variable `ACQ_BATCH_HPAN_LIST_DATE_VALIDATION` from `true` to `false`
The service that used to generate the hashpans file it is no longer available and the batch service does not need the file to make the ADE flow working. In order to avoid the error generation _Recovered PAN list exceeding a day_ it is required to disable the date validation on the hashpan file.
=> [RTD-393] disable date validation on hpans by default

app/src/main/resources/config/application.yml, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml
This PR proposes to disable the checksum validation on hpans file by default.
- Changed the env var `ACQ_BATCH_HPAN_LIST_CHECKSUM_VALIDATION` from `true` to `false`
The checksum cannot be generated by the pipeline that will generate the hashpan file. Therefore the batch service must disable this check to avoid errors during the processing.
=> [RTD-400] disable checksum validation on hpans by default

app/src/main/resources/config/application.yml, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml
This PR proposes to replace the default endpoints of hashed-pans and salt with v2 version. The salt endpoint has been parametrized alike the hpans one.
- Update application files 
The informally v1 endpoints are deprecated and must be replaced with the v2 ones. The url salt parametrization may be useful in the future to avoid dedicated release of the batch service to change the api version.
=> [RTD-402] parametrize url salt and set v2 endpoint by default

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java, api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemProcessListener.java, api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/TransactionAggregationReaderProcessor.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/config/LoggerRule.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/listener/TransactionItemProcessListenerTest.java
This PR proposes to add the logging during the ade file processing, in particular the validation errors. Plus 
- Add processor listener to ade
- Minor fix on file log naming
- Minor improvement on code readability
The acquirers needs a way to understand easily what went wrong during the file processing therefore it is required a better logging. The validation errors have been added to the logs to let the acquirers know if the file presents any problem.
=> [RTD-474] Improve validation errors logging on ADE

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/EnforceSenderCodeUniquenessTasklet.java
This PR proposes to improve the log clearness of the sender code uniqueness check. 
- Add log message in sender code check
When the input file is empty or all records have been discarded during processing, the sender code uniqueness check fails and shows an unclear log message. The two use cases mentioned before deserve a dedicated log message to improve the understandability of batch service processes.
=> [RTD-473] improve clearness of sender code uniqueness check log

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/encryption/EncryptUtil.java
This PR proposes to remove two security hotspots generated by sonar regarding the print of a stack trace.
- Remove `printStackTrace` and replace with a `log.error` of the message
The print of a stack trace is not a good and safe solution and therefore it must be avoided.
=> [RTD-503] remove print stack traces

api/batch/src/main/resources/config/panReaderStep.properties, app/src/main/resources/config/application.yml, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml
This PR proposes to use distinct variables to pilot different property. Plus the `ACQ_BATCH_INPUT_SKIP_LIMIT` default value has been set to 0.
- Used distinct variables for different properties
- Set input skip limit to 0
The overwrite of some environment variables may cause to alter the behaviour of different parts of the batch service. For that reason it is better to separate the variables that pilot different properties.
=> [RTD-454] split env variables that pilot two different properties

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTasklet.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/FileManagementTaskletTest.java
This PR proposes to fix a bug with the file management step. The output files get archived in success / error directory instead of getting piloted by the appropriate env var `ACQ_BATCH_DELETE_OUTPUT_FILE`.
- Changed `FileManagementTasklet`
- Updated unit test to verify the output directory
The last feature pointed out a bad file management in the dedicated task. It's been introduced a flag to manage the output files in an appropriate way. 
As consequence the mechanism which moved the `.pgp` files into success directory is no longer valid and those files are handled by the same env var mentioned before.
=> fix: [RTD-733] fix output archived after batch service

acceptance_tests/sender_code_not_associated/script_sender_code_not_associated.bash
This PR proposes to fix the assertion in the "sender code not associated" acceptance test.
- changed test script
The assertion was bad formulated because it checked on 400 status code (instead of 401) and it did not consider the retry mechanism of batch service that cause multiple occurrence of the error status code.
=> fix: [RTD-673] fix sender code non associated assertion

acceptance_tests/ingestion_big_files/script_ingestion.bash
This PR proposes to fix the ingestion script with the correct naming convention and to parametrize che test timeout. 
- Fix naming convention
- Parametrize test timeout
The pipelines take around 180-190 minutes to complete, then the new default value has been set to 250 minutes. The naming convention has been adapted to the decrypter one.
=> fix: [RTD-674] change naming convention and parametrize timeout

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTasklet.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/tasklet/SenderAdeAckFilesRecoveryTaskletTest.java
This PR proposes to add the error handling in case a ade ack file has already been downloaded by the sender.
- added try-catch for specific exception
- added test case
When the batch service tries to download an ade-ack already downloaded in a previous run, then a FileExistsException is thrown. In order to handle the error case (and exception log), a try-catch has been added.
=> fix: [RTD-849] mitigation on sender ade ack file already exists exception

app/src/main/resources/config/application.yml, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml
This PR proposes to align the sender-ade-ack property definition inside the application.yml with the one defined in the submodule integration.rest. (`rest-client.sender-ade-ack` instead of `rest-client.hpan.sender-ade-ack`)
- changed property definition in application.yml
The property read is different from the one defined in the application.yml.
=> fix: [RTD-845] fix sender-ade-ack property path level

pom.xml
This PR proposes to fix the CVEs on jackson package with a bump from version 2.13.4 to 2.14.0.
- Version upgrade in pom 
- Parametrization of explicit version dependencies
Jackson CVEs are now solved.
=> fix: [RTD-876] fix cve jackson with bump version from 2.13.4 to 2.14.0

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/model/InboundTransaction.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/step/processor/InboundTransactionItemProcessorValidatorTest.java
This PR proposes to add a validation on the field `amount` of the input transaction file. Min value admitted is 0 and max value is 10^11 -1 (99.999.999.999).
- add the field validation and related unit tests
The amount field needs to have a maximum and minimum value admitted.
=> feat: [RTD-954] add min and max validation on amount input field

acceptance_tests/file_report/file_report_more_sender_codes.bash
This PR proposes to add an acceptance test for file report feature.
- add acceptance test
With this change we can test the behavior of the batch service in case of files sent with multiple sender code, expecting a single report containing both of them.
The prerequisite is that the used API key must be associated with both sender codes in sender auth.
=> chore: [RTD-1121] Test multiple senders in file report

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java, integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientTest.java
This PR proposes to handle the response error code 409 on the upload api. 
The batch service won't retry the upload, won't move the file `into` pending folder but only log an error.
- changes on error code conditional flow
- updated unit test
The error code 409 means a file with the same name has already been uploaded and the PUT api will keep failing. Besides, when an upload fails the file is moved to the `pending` folder, this must not happen in case of 409.
=> feat: [RTD-1134] handle put error status 409

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/TransactionFilterStep.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchFileReportTest.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java, integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/model/FileReport.java, integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/FileReportRestClientTest.java
This PR proposes to maintain the row sorting of the file report between the JSON and the file saved. 
- Remove the task executor of the item writer step
- Refactor from Collection to List datatype to maintain the row sorting
The batch service must save the file report on file with the same file sorting received in the JSON.
=> fix: [RTD-1215] fix rows order in file report

integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/HpanRestClientImpl.java
This PR proposes to replace the `java.io` library with `java.nio` library to create a temporary file. The nio library solve a security hotspot warned by SonarCloud.
=> fix: [RTD-540] use nio library to create temp file

api/batch/pom.xml, api/pom.xml, app/pom.xml, app/src/main/resources/config/application.yml, core/pom.xml, integration/jpa/pom.xml, integration/pom.xml, integration/rest/pom.xml, integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientImpl.java, integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/logger/MaskingPatternLayoutTest.java, ops_resources/example_config/application.yml, ops_resources/example_config/application_hbsql.yml, pom.xml
This PR proposes to reduce the log severity from `error` to `warn` in case of failure of ack confirm api.
Bump pom version to 2.0.3 for next release
=> fix: [RTD-1655] reduce log severity on ack confirm failure

api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatch.java, api/batch/src/test/java/it/gov/pagopa/rtd/transaction_filter/batch/TransactionFilterBatchTest.java, integration/rest/src/main/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientImpl.java, integration/rest/src/test/java/it/gov/pagopa/rtd/transaction_filter/connector/SenderAdeAckRestClientTest.java
This PR proposes to fix a bug in the conditional flow after the ade-ack download step. Atm when the ade-ack-list step fails the filemanagement step is skipped and the job ends. Desiderata is: when ade-ack-list step fails then the filemanagement step is executed.
=> fix: [RTD-1669] fix conditional flow after ack fails

Dockerfile, api/batch/pom.xml, api/pom.xml, app/pom.xml, core/pom.xml, integration/jpa/pom.xml, integration/pom.xml, integration/rest/pom.xml, pom.xml
This PR proposes to bump dependencies to solve CVE.
| Dependency | Previous version | Updated version | 
| --- | --- | --- |
| `amazoncorretto` | `17.0.8-alpine3.18` | `17.0.10-alpine3.19` |
| `spring-boot-starter-parent` | `3.1.3` | `3.2.2` |
| `springframework-cloud` | `4.0.4` | `4.1.0` |
With this change we remove the currently found CVE.
=> fix: [RTD-2347] Fix high CVE on Logback and OpenSSL dependencies

.github/workflows/scan.yml
This PR proposes to fix the github workflow responsible to send the slack notification when there are CRITICAL or HIGH CVEs.
=> chore: fix slack notification send when CVEs are detected
